# Generated by Django 4.2 on 2023-04-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("bio", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField()),
                (
                    "authors",
                    models.ManyToManyField(
                        related_name="works", to="discipline.person"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="teams", to="discipline.person"
                    ),
                ),
                (
                    "works",
                    models.ManyToManyField(
                        blank=True, related_name="teams", to="discipline.work"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Discipline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("introduction", models.TextField()),
                (
                    "key_figures",
                    models.ManyToManyField(
                        related_name="key_figures", to="discipline.person"
                    ),
                ),
                (
                    "parents",
                    models.ManyToManyField(
                        blank=True,
                        related_name="subdisciplines",
                        to="discipline.discipline",
                    ),
                ),
                (
                    "works",
                    models.ManyToManyField(
                        related_name="disciplines", to="discipline.work"
                    ),
                ),
            ],
        ),
    ]
