# Generated by Django 4.2 on 2023-04-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discipline", "0003_discipline_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person", old_name="name", new_name="first_name",
        ),
        migrations.AddField(
            model_name="person",
            name="last_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
