# Generated by Django 4.2 on 2023-04-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discipline", "0004_rename_name_person_first_name_person_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person", name="bio", field=models.TextField(blank=True),
        ),
    ]
