# Generated by Django 4.2 on 2023-04-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discipline", "0005_alter_person_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="team", name="introduction", field=models.TextField(blank=True),
        ),
    ]
