# Generated by Django 4.2 on 2023-04-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discipline", "0006_team_introduction"),
    ]

    operations = [
        migrations.CreateModel(
            name="Institute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("link", models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="team", name="link", field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="person",
            name="institute",
            field=models.ManyToManyField(
                blank=True, related_name="persons", to="discipline.institute"
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="institute",
            field=models.ManyToManyField(
                blank=True, related_name="teams", to="discipline.institute"
            ),
        ),
    ]
