# Generated by Django 4.2 on 2023-04-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discipline", "0007_institute_team_link_person_institute_team_institute"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("link", models.URLField()),
                ("body", models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="discipline",
            name="research_teams",
            field=models.ManyToManyField(
                blank=True, related_name="disciplines", to="discipline.team"
            ),
        ),
        migrations.AddField(
            model_name="discipline",
            name="news",
            field=models.ManyToManyField(
                blank=True, related_name="disciplines", to="discipline.news"
            ),
        ),
    ]
