# Generated by Django 4.2 on 2023-04-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discipline", "0009_edsource_alter_discipline_key_figures_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("link", models.URLField()),
                ("body", models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="edsource",
            name="institute",
            field=models.ManyToManyField(
                blank=True, related_name="edsources", to="discipline.institute"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="first_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="person",
            name="last_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name="discipline",
            name="videos",
            field=models.ManyToManyField(
                blank=True, related_name="disciplines", to="discipline.video"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="videos",
            field=models.ManyToManyField(
                blank=True, related_name="persons", to="discipline.video"
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="videos",
            field=models.ManyToManyField(
                blank=True, related_name="works", to="discipline.video"
            ),
        ),
    ]
